# Generated by Django 3.1.7 on 2021-03-12 04:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('parent_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.object')),
                ('friendly_name', models.CharField(default='<django.db.models.fields.CharField>', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.datatype')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.object')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('object_uid', models.BigIntegerField()),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.field')),
                ('object', models.ManyToManyField(to='asset.Object')),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'unique_together': {('object_uid', 'field_id')},
            },
        ),
        migrations.CreateModel(
            name='LongText',
            fields=[
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='asset.data')),
                ('value', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ShortText',
            fields=[
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='asset.data')),
                ('value', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDataLink',
            fields=[
                ('object_uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('parent_object_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.objectdatalink')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.object')),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='object_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.objectdatalink'),
        ),
        migrations.RemoveField(
            model_name='data',
            name='object',
        ),
        migrations.CreateModel(
            name='Boolean',
            fields=[
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='asset.data')),
                ('value', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='asset.data')),
                ('value', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='asset.data')),
                ('value', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='asset.data')),
                ('value', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Integer',
            fields=[
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='asset.data')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PositiveInteger',
            fields=[
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='asset.data')),
                ('value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='asset.data')),
                ('value', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='asset.data')),
                ('value', models.ImageField(upload_to='')),
            ],
        ),
    ]
