# Generated by Django 3.1.7 on 2021-06-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='slug',
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.SlugField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.SlugField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
